# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "DNS-API"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

#
# Setting this will ensure that redirection links, etc, will have
# the correct hostname.  It doesn't handle getting the real IP
# from the proxy though, instead see the next setting.
#
behind_proxy: true

#
# This will allow the real remote IP to be determined and logged.
#
plack_middlewares:
      -
          - ReverseProxy

